export const AUTH = {
    LOGIN_REQUEST: 'LOGIN_REGUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE'
}

export const CHAT = {
    GET: 'get',
    POST: 'post',
    GET_REQUEST: 'GET_REQUEST',
    GET_SUCCESS: 'GET_SUCCESS',
    GET_FAILURE: 'GET_FAILURE',
    POST_REQUEST: 'POST_REQUEST',
    POST_SUCCESS: 'POST_SUCCESS',
    POST_FAILURE: 'POST_FAILURE'
}

export const LOADING = {
    IS: 'LOADING',
    ISNOT: 'LOADED'
}

export const INPUT = {
    ENABLE: 'INPUT_ENABLE',
    DISABLE: 'INPUT_DISABLE'
}